### ISSUE TITLE
Farmer's delight compat issues

### ISSUE THREAD

**Issue by Sailingway** [BelgianSalamander/MoreBundles#6] opened 2021-12-19 10:07 UTC
Game crashes with farmer's delight
[crash-2021-12-19_16.00.56-server.txt](https://github.com/BelgianSalamander/MoreBundles/files/7740605/crash-2021-12-19_16.00.56-server.txt)
[crash-2021-12-19_16.00.59-client.txt](https://github.com/BelgianSalamander/MoreBundles/files/7740606/crash-2021-12-19_16.00.59-client.txt)

**Comment by BelgianSalamander** [comment] 2021-12-19 21:12
The client crash log doesn't mention More Bundles, it mentions Sodium. However, it is still possible that my mod may have caused that crash in a way. The server crash is definitely More Bundles fault and the root of the issue seems to be the same as this issue: https://github.com/BelgianSalamander/MoreBundles/issues/7. The error seems to be caused by farmer's delight adding a "Dispenser Behavior" before More Bundles has properly initialized and so the config. I should be able to fix this by loading the config as soon as it is needed even if it is before mod initialization.

**Comment by BelgianSalamander** [comment] 2021-12-19 21:48
I have been able to reproduce the crash and have now fixed it I will update the curseforge page soon.

**Comment by BelgianSalamander** [comment] 2021-12-19 22:34
This should be fixed in this version (https://www.curseforge.com/minecraft/mc-mods/more-bundles/files/3573607). Could you test it so I can close the issue? Thanks!

**Comment by Sailingway** [comment] 2021-12-20 00:05
Yep, it works. Thank you for your hard work!

**Closed as completed** 2021-12-20 00:59 UTC
