### ISSUE TITLE
Mixin error on 1.18.2

### ISSUE THREAD

**Issue by Sunconure11** [BelgianSalamander/MoreBundles#12] opened 2022-04-15 09:56 UTC
https://pastebin.com/zu06iugL

@BelgianSalamander

**Comment by gliscowo** [comment] 2022-04-15 14:54
Author of Alloy Forgery here, as this issue has also been raised on our repo and we've done some investigating. Your mixin plugin accidentally [seals the the EnchantmentTarget class](https://github.com/BelgianSalamander/MoreBundles/blob/f1587cf8f0b1fd97223151e9bd0324b06764dba3/Fabric/src/main/java/me/salamander/morebundles/mixin/asm/MixinASMPlugin.java#L47), making it so no other mod can  add their own enchantment target after More Bundles has loaded. We've haven't yet tested this in the proper modpack layout, but we have confirmed that the entire mixin plugin can safely be dropped and the mod will still work just fine. As such, I recommend simply removing it as that will most likely also resolve this issue.
Have a great Day

**Comment by BelgianSalamander** [comment] 2022-04-15 21:31
Since Java 17 (which is used since minecraft 1,18), all abstract enum classes are sealed by default which broke manigham mills mechanism of adding values to such enums (https://github.com/Chocohead/Fabric-ASM/issues/11). Since I was using this library to add an enchantment target of bundles in 1.17, I kept using it in 1.18 and fixed the issue by adding the plugin which set the permitted subclasses of EnchantmentTarget to all of its inner classes (because mm does add to the inner classes). With only this mod, removing the plugin reintroduces the problem with mm. However, it may be possible that the class is getting unsealed by some mechanism and my plugin would be resealing it which obviously is not the greatest of things. I have adapted the plugin so that it first checks whether EnchantmentTarget has any permitted subclasses (which is how the JVM checks for sealed classes) before adding its own permitted subclasses which could "re-seal" it accidentaly. Hopefully this works :)

Also, the mod currently does not support 1.18.2 (although I will update it shortly with this bugfix)

Thanks

**Comment by gliscowo** [comment] 2022-04-15 21:37
After looking at the issue you linked, it seems a much easier fix for this is to simply create an accesswidener that strips the seal from the class. This is also more compatible, as it can never possibly run into a situation where the class is unintentionally re-sealed - this is also how other mods have approached this problem
Cheers

**Comment by BelgianSalamander** [comment] 2022-04-15 21:39
Oh I seem to have completely forgotten about that. I will do that instead

**Comment by LaylBongers** [comment] 2022-04-22 23:12
Making this change (to using access wideners) will also make this mod compatible with the Quilt loader, as currently the use of `FabricLoader`'s internals for this makes it incompatible.

**Comment by BelgianSalamander** [comment] 2022-12-05 00:08
This should be fixed on the latest version.

**Closed as completed by BelgianSalamander** 2022-12-05 00:08 UTC
